// Generated by gencpp from file plumbing_server_client/add_init.msg
// DO NOT EDIT!


#ifndef PLUMBING_SERVER_CLIENT_MESSAGE_ADD_INIT_H
#define PLUMBING_SERVER_CLIENT_MESSAGE_ADD_INIT_H

#include <ros/service_traits.h>


#include <plumbing_server_client/add_initRequest.h>
#include <plumbing_server_client/add_initResponse.h>


namespace plumbing_server_client
{

struct add_init
{

typedef add_initRequest Request;
typedef add_initResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_init
} // namespace plumbing_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::plumbing_server_client::add_init > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::plumbing_server_client::add_init&) { return value(); }
};

template<>
struct DataType< ::plumbing_server_client::add_init > {
  static const char* value()
  {
    return "plumbing_server_client/add_init";
  }

  static const char* value(const ::plumbing_server_client::add_init&) { return value(); }
};


// service_traits::MD5Sum< ::plumbing_server_client::add_initRequest> should match
// service_traits::MD5Sum< ::plumbing_server_client::add_init >
template<>
struct MD5Sum< ::plumbing_server_client::add_initRequest>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::add_init >::value();
  }
  static const char* value(const ::plumbing_server_client::add_initRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::add_initRequest> should match
// service_traits::DataType< ::plumbing_server_client::add_init >
template<>
struct DataType< ::plumbing_server_client::add_initRequest>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::add_init >::value();
  }
  static const char* value(const ::plumbing_server_client::add_initRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::plumbing_server_client::add_initResponse> should match
// service_traits::MD5Sum< ::plumbing_server_client::add_init >
template<>
struct MD5Sum< ::plumbing_server_client::add_initResponse>
{
  static const char* value()
  {
    return MD5Sum< ::plumbing_server_client::add_init >::value();
  }
  static const char* value(const ::plumbing_server_client::add_initResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::plumbing_server_client::add_initResponse> should match
// service_traits::DataType< ::plumbing_server_client::add_init >
template<>
struct DataType< ::plumbing_server_client::add_initResponse>
{
  static const char* value()
  {
    return DataType< ::plumbing_server_client::add_init >::value();
  }
  static const char* value(const ::plumbing_server_client::add_initResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMBING_SERVER_CLIENT_MESSAGE_ADD_INIT_H
